spring.application.name=myreturn

spring.datasource.url=jdbc:mysql://localhost:3307/myreturn
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.main.allow-bean-definition-overriding=true

# Twelve Data API Configuration
twelvedata.api.key=your_api_key_here

# Groww API Configuration
groww.api.key=eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NTMxNDQyMDAsImlhdCI6MTc1MzExMzMyMiwibmJmIjoxNzUzMTEzMzIyLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCI0NzUxNmNmYy1jNmFiLTQyNTEtYTM3ZC0yY2I0NjdhMjQ3N2ZcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiYmI0MDkxOTEtNzIxNC00ODMyLWE5NzMtMmIyMDIxYjkwNzMyXCIsXCJkZXZpY2VJZFwiOlwiNmIxZmJhY2YtYjJmYS01YmUxLTg4ZTAtM2M5MGQ3MzZkMjgxXCIsXCJzZXNzaW9uSWRcIjpcIjJlOTRmOGViLTUwYjYtNDNjNS1hZGVlLTgyMzNmMTEyNzRiNVwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYk5kQXc3ZXk0RVB2Y1RLZzFBNGJDQjlSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcIm9yZGVyLWJhc2ljLGxpdmVfZGF0YS1iYXNpYyxub25fdHJhZGluZy1iYXNpYyxvcmRlcl9yZWFkX29ubHktYmFzaWNcIixcInNvdXJjZUlwQWRkcmVzc1wiOlwiMTAzLjIxNS4yMzcuMzEsMTcyLjY4Ljc5LjE3NSwzNS4yNDEuMjMuMTIzXCIsXCJ0d29GYUV4cGlyeVRzXCI6MTc1MzE0NDIwMDAwMH0iLCJpc3MiOiJhcGV4LWF1dGgtcHJvZC1hcHAifQ.snmewFWWxyyiZ6CB_JLGq5bKvoZKShKsvM9QLswFQr4tR4gaoSI0OIIQZk3uU95cR93xzUPTDabDX834G4CN3g
groww.api.secret=V5E4VU2JS3ZTTI4CPN25JVOIOXUEYQUL
