package com.example.myreturn.util;

import java.util.Arrays;
import java.util.List;

public class NiftySymbols {
    
    
    public static final List<String> NIFTY_500 = Arrays.asList(
        "GMDCLTD","SAREGAMA","SAMMAANCAP",
        "CHENNPETRO","PVRINOX","WELSPUNLIV","DALBHARAT","JUBLPHARMA","WHIRLPOOL","TRITURBINE","NMDC"
        ,"SUMICHEM","SAIL","RAYMOND","WIPRO","GPPL","KIMS","BAJFINANCE","LTF","TATACOMM","MAPMYINDIA"
        ,"MSUMI","TATASTEEL","CAMPUS","INDHOTEL","APTUS","ANANDRATHI","GODFRYPHLP","HDFCAMC","FLUOROCHEM"
        ,"GODREJAGRO","ECLERX","GODREJPROP","IIFL","LATENTVIEW","MRPL","POONAWALLA","HCLTECH","PERSISTENT",
        "JKCEMENT","INDIAMART","AADHARHFC","INDUSINDBK","JSWSTEEL","PATANJALI","INDIGO","GILLETTE","NESTLEIND"
        ,"ONGC","LALPATHLAB","ZENTEC","GODREJIND","CHALET","SUNDARMFIN","MANKIND","EXIDEIND","TANLA","COALINDIA",
        "SCHNEIDER","SWIGGY","EMAMILTD","SCHAEFFLER","LAURUSLABS","DEVYANI","UTIAMC","JPPOWER","ICICIBANK","RHIM",
        "TORNTPHARM","OFSS","BIKAJI","BIOCON","POLYCAB","AFCONS","JINDALSTEL","REDINGTON","KPIL","VMM","HINDCOPPER",
        "NETWORK18","OIL","TRIVENI","LODHA","INFY","SIEMENS","DCMSHRIRAM","ASTRAL","YESBANK","VEDL","AMBUJACEM",
        "BALRAMCHIN","RRKABEL","ABB","NATCOPHARM","NSLNISP","BALKRISIND","GPIL","MFSL","CGCL","PAYTM","HINDALCO"
        ,"DELHIVERY","APARINDS","M&M","UNIONBANK","MANAPPURAM","BANDHANBNK","BAJAJ-AUTO","THERMAX","ABSLAMC",
        "KAJARIACER","GRAVITA","SIGNATURE","BAJAJFINSV","SKFINDIA","ULTRACEMCO","CIPLA","JSL","AIIL","WELCORP"
        ,"IGIL","OLECTRA","SJVN","J&KBANK","ITI","RELIANCE","ESCORTS","VGUARD","FEDERALBNK","INDGN","AMBER",
        "EIDPARRY","COLPAL","IOB","NETWEB","SONATSOFTW","BAYERCROP","DABUR","JINDALSAW","KNRCON","LT",
        "GLENMARK","SHREECEM","JMFINANCIL","EMCURE","GAIL","JSWENERGY","NH","TATAMOTORS","NTPC","DMART",
        "TATAELXSI","MMTC","OBEROIRLTY","ASTERDM","CAPLIPOINT","ZEEL","LLOYDSME","ELGIEQUIP","MUTHOOTFIN",
        "LEMONTREE","ACC","IPCALAB","GNFC","RECLTD","ABBOTINDIA","GODIGIT","CUMMINSIND","TIMKEN","LINDEINDIA",
        "PNB","GRAPHITE","KEI","GLAND","DRREDDY","PIIND","PTCIL","3MINDIA","HINDZINC","VTL","MARUTI","RTNINDIA",
        "COFORGE","SARDAEN","ACE","CANFINHOME","BLUEDART","ITC","PRESTIGE","GESHIP","ALKEM","SWANENERGY","DLF",
        "ZYDUSLIFE","LICI","EICHERMOT","AJANTPHARM","ERIS","SUNPHARMA","ADANIPOWER","NATIONALUM","ZENSARTECH",
        "JIOFIN","APOLLOHOSP","MPHASIS","SOBHA","ARE&M","SUNTV","JUBLINGREA","IRB","CRISIL","IDFCFIRSTB","GMRAIRPORT",
        "JSWINFRA","TCS","AEGISLOG","BHARTIARTL","UCOBANK","DEEPAKNTR","ADANIENSOL","SAILIFE","TARIL","BHARATFORG",
        "BAJAJHFL","JWL","MCX","ZFCVINDIA","SRF","CAMS","RKFORGE","STARHEALTH","UBL","NIACL","KANSAINER","TATACONSUM",
        "NCC","SBIN","ADANIPORTS","KEC","RAINBOW","TRIDENT","HYUNDAI","M&MFIN","LTTS","BATAINDIA","APLLTD","ALIVUS",
        "TIINDIA","INDUSTOWER","ETERNAL","JYOTHYLAB","BHARTIHEXA","PFIZER","ASIANPAINT","NHPC","IRFC","KFINTECH","PCBL"
    );
    // ,"IOC","CEATLTD","BERGEPAINT","GSPL","ABFRL","KARURVYSYA","RITES","AAVAS","AUBANK","TECHNOE","JBCHEPHARM",
    // "CASTROLIND","APOLLOTYRE","HINDUNILVR","SAPPHIRE","BANKBARODA","ADANIENT","HAPPSTMNDS","SBILIFE","BOSCHLTD"
    // ,"BANKINDIA","METROPOLIS","HONAUT","TECHM","CDSL","TATACHEM","CHOLAFIN","TATAINVEST","DOMS","IDEA","360ONE"
    // ,"SCI","POWERGRID","HSCL","EIHOTEL","CARBORUNIV","TRENT","MAHABANK","INDIACEM","CRAFTSMAN","HEROMOTOCO"
    // ,"KPITTECH","JSWHL","DIXON","UPL","INDIANB","MGL","CHOLAHLDNG","BLS","JBMA","TBOTEK","HAVELLS","BRITANNIA"
    // ,"CANBK","TVSMOTOR","NAM-INDIA","BPCL","BSE","PEL","TITAN","BHEL","RADICO","VBL","PIDILITIND","PNCINFRA",
    // "ASHOKLEY","IRCTC","WESTLIFE","PHOENIXLTD","IFCI","ELECON","CONCORDBIO","CESC","FSL","PFC","ATGL","DIVISLAB"
    // ,"SUPREMEIND","CENTRALBK","RAILTEL","NAUKRI","GRANULES","PNBHOUSING","PRAJIND","USHAMART","POLICYBZR",
    // "CHAMBLFERT","LTFOODS","SONACOMS","IDBI","UNITDSPR","JYOTICNC","LUPIN","NTPCGREEN","ACMESOLAR","RENUKA"
    // ,"HUDCO","HFCL","KPRMILL","BASF","AKUMS","SYRMA","JUBLFOOD","INOXINDIA","IREDA","CONCOR","AUROPHARMA"
    // ,"TORNTPOWER","IEX","HBLENGINE","GUJGASLTD","NAVA","GLAXO","MAHSEAMLES","NUVAMA","TEJASNET","ENDURANCE"
    // ,"LTIM","FACT","MINDACORP","GRASIM","CREDITACC","JUSTDIAL","TATAPOWER","VOLTAS","NBCC","PAGEIND","IKS"
    // ,"GICRE","AWL","MOTHERSON","RCF","BBTC","FORTIS","NIVABUPA","RPOWER","FIRSTCRY","ICICIPRULI","VIJAYA",
    // "MRF","CYIENT","HDFCBANK","MASTEK","JKTYRE","DEEPAKFERT","IRCON","COROMANDEL","SHYAMMETL","LICHSGFIN",
    // "SAGILITY","GRSE","POLYMED","INTELLECT","TTML","SOLARINDS","CENTURYPLY","KOTAKBANK","APLAPOLLO","RVNL"
    // ,"SBICARD","SUNDRMFAST","KAYNES","MANYAVAR","CROMPTON","INOXWIND","CUB","SUZLON","KALYANKJIL","HDFCLIFE"
    // ,"MEDANTA","ABCAPITAL","ICICIGI","SYNGENE","IGL","FINPIPE","TATATECH","MARICO","CERA","BLUESTARCO"
    // ,"FINCABLES","ADANIGREEN","BAJAJHLDNG","HINDPETRO","BSOFT","SBFC","KIRLOSENG","AFFLE","RAMCOCEM"
    // ,"GODREJCP","BRIGADE","NEULANDLAB","ENGINERSIN","COHANCE","ANANTRAJ","NAVINFLUOR","MAXHEALTH"
    // ,"ABREL","MAZDOCK","MOTILALOFS","PETRONET","POWERINDIA","HEG","TITAGARH","CCL","AIAENG","OLAELEC"
    // ,"AARTIIND","FIVESTAR","BEL","ANGELONE","GVT&D","PREMIERENE","NLCINDIA","DBREALTY","RAYMONDLSL"
    // ,"PGEL","NYKAA","WOCKPHARMA","COCHINSHIP","PPLPHARMA","HOMEFIRST","UNOMINDA","RBLBANK","ASTRAZEN"
    // ,"WAAREEENER","HAL","ALKYLAMINE","HONASA","SHRIRAMFIN","KIRLOSBROS","BEML","CGPOWER","ASAHIINDIA"
    // ,"BDL","SWSOLAR","DATAPATTNS","ATUL","ROUTE","AXISBANK","ALOKINDS","NEWGEN","CLEAN"

    public static List<String> getNifty500() {
        return NIFTY_500;
    }
    
    public static int getNifty500Count() {
        return NIFTY_500.size();
    }
} 